### ISSUE TITLE
Task 'bintrayUpload' not found in root project 'bin'

### ISSUE THREAD

**Issue by vipulasri** [danielemaddaluno/gradle-jcenter-publish#1]
I Followed Every step needed to publish my AAR file to JCenter and then synchronize it with Maven Central. I wrote this command to follow his step 13 and step 14 and got this error:

G:\Android Development Application\android-studio\gradle\gradle-2.2.1\bin>gradle bintrayUpload

FAILURE: Build failed with an exception.

```
What went wrong:
Task 'bintrayUpload' not found in root project 'bin'.
```
##### build.gradle(Project: xxxx)

``` xml
buildscript {
repositories {
    jcenter()
}
dependencies {
    classpath 'com.android.tools.build:gradle:1.1.2'
    classpath 'com.github.dcendents:android-maven-plugin:1.2'
    classpath "com.jfrog.bintray.gradle:gradle-bintray-plugin:1.1"

    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files
}
}

allprojects {

apply plugin: 'com.jfrog.bintray'

repositories {
    jcenter()
}
}
```

**Comment by iamcrypticcoder** [comment]
Hi @vipulasri , Would you please tell me how did you solve it ?

**Comment by vipulasri** [comment]
@imcrypticcoder check this [SO Answer](http://stackoverflow.com/questions/29715851/task-bintrayupload-not-found-in-root-project-bin)
